name: Build and Deploy RepoTracker Application

on:
  push:
    branches:
      - main

jobs:
  build-deploy:
    name: Build and Deploy repoTracker application
    runs-on: ubuntu-latest
    steps:
      - name: checkout branch
        uses: actions/checkout@v4

      - name: setup JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'corretto'
          java-version: '17'

      - name: Build the application
        run: |
          mvn clean
          mvn -B package --file pom.xml

      - name: build the docker image
        id: build-docker-image
        run: |
          ls -la 
          docker build . -f Dockerfile -t ${{ secrets.DOCKER_HUB_USERNAME }}/repotracker:latest

      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: push the docker image
        id: push-docker-image
        run: docker push ${{ secrets.DOCKER_HUB_USERNAME }}/repotracker:latest
